config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/index'
  root 'welcome#index'

  resources :users do
    resources :messages
    resources :friendships
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :me, class_name: "User"
  belongs_to :friend, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :fullname,  presence: true, length: { maximum: 25 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :friendships, foreign_key: "me_id", dependent: :destroy
  has_many :friends, through: :friendships


  def befriend(other_user)
    friends << other_user
  end

  def defriend(other_user)
    friends.delete(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
before_action :authenticate_user!


  def index
    @users = User.all
  end


  def create
    user = User.find(params[:friend_id])
    current_user.befriend(user)
    user.befriend(current_user)
    redirect_to user_friendships_path(current_user)
  end

  def destroy
    user = Friendship.find(params[:id]).friend
    current_user.defriend(user)
    user.defriend(current_user)
    redirect_to user_friendships_path(current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :authenticate_user!

  def new
    @user = User.find(current_user.id)
  end

  def index
    @user = User.find(current_user.id)
    @messages = Message.where("user_id IN (?) OR user_id = ?", @user.friends.ids, @user.id).paginate(:page => params[:page], :per_page => 2)
  end

  def create
    @user = User.find(current_user.id)
    @message = @user.messages.create(message_params)
    redirect_to root_url
  end

  private
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :fullname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.paginate(:page => params[:page], :per_page => 2)
  end

  def show
    @user = User.find(current_user.id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/index.html.erb
<h1>Friendships index</h1>
<p>Currently logged in as user: <%= current_user.fullname %></p>

<table>
<% @users.each do |user| %>
  <% if user.fullname != current_user.fullname %>
    <tr>
      <td><%= user.fullname %></td>
        <% if current_user.friends.include?(user) %>
          <td>This is a friend</td>
          <td>
            <%= button_to("Defriend", [current_user, current_user.friendships.find_by(friend_id: user.id)], method: :delete ) %>
          </td>
        <% else %>
          <td>This is not a friend</td>
          <td>
            <%= button_to("Befriend", [current_user, current_user.friendships.build], params: { friend_id: user.id }, method: :post ) %>
          </td>
  
        <% end %>
    </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'Back to home', root_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbcapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>View your messages</h1>
<p>Currently logged in as user: <%= current_user.fullname %></p>


<table>
<% @messages.each do |message| %>
  <tr>
    <td><%= message.content %></td>
    <td>Written by <%= message.user.fullname %></td>
  </tr>
<% end %>
</table>


<%= will_paginate @messages %>

<%= link_to 'Back to home', root_url %>

app/views/messages/new.html.erb
<h1>Post new message</h1>
<p>Currently logged in as <%= current_user.fullname %></p>

<%= form_with(model: [ @user, @user.messages.build ], local: true) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_field :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Home', root_url %>

app/views/users/index.html.erb
<h1>View all users</h1>
<p>Currently logged in as user: <%= current_user.fullname %></p>

<%= will_paginate @users %>

<table>
<% @users.each do |user| %>
  <tr>
    <td><%= user.fullname %></td>
      <% if current_user.friends.include?(user) %>
        <td>This is a friend</td>
      <% else %>
        <td>This is not a friend</td>
      <% end %>
  </tr>
<% end %>
</table>


<%= link_to 'Back to home', root_url %>

app/views/users/show.html.erb
<h1>Page for the current user</h1>
<p>
  User currently logged in: <%= current_user.fullname %>
</p>


<%= link_to 'Home', root_url %>

app/views/welcome/index.html.erb
<title>Fbcapp</title>
<h1>This is Fbcapp</h1>
<p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.fullname %></strong>.
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <%= link_to "View users", users_path %>
  <%= link_to "View friendships", user_friendships_path(current_user) %>
  <%= link_to "Personal page", user_path(current_user) %>
  <%= link_to "View your messages", user_messages_path(current_user) %>
  <%= link_to "Post message", new_user_message_path(current_user) %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Login", new_user_session_path %>
<% end %>
</p>